version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - /
      - /demos/*/
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/demos/graphql-demo/ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/demos/moderator"
    schedule:
      interval: "daily"
